// GENERATED from docs/TILES.md by `npm run tiles`. Don't edit: change docs/TILES.md and run it again.
// 297 value(s) still TODO: copy them from the player mat into docs/TILES.md.

import { todo, type TileTable } from './tileTable'

export const TILE_TABLE: TileTable = {
  industries: {
    cotton: {
      total: 12,
      levels: [
        {
          level: 1,
          locked: false,
          tiles: todo("Cotton mill I: tiles"),
          money: todo("Cotton mill I: £ cost"),
          coal: todo("Cotton mill I: coal"),
          iron: todo("Cotton mill I: iron"),
          vp: 5,
          income: todo("Cotton mill I: income"),
          link: todo("Cotton mill I: link value"),
          cubes: null,
          noCanal: todo("Cotton mill I: not in canal era"),
          noRail: todo("Cotton mill I: not in rail era"),
          developable: todo("Cotton mill I: developable"),
        },
        {
          level: 2,
          locked: false,
          tiles: todo("Cotton mill II: tiles"),
          money: todo("Cotton mill II: £ cost"),
          coal: todo("Cotton mill II: coal"),
          iron: todo("Cotton mill II: iron"),
          vp: todo("Cotton mill II: VP"),
          income: todo("Cotton mill II: income"),
          link: todo("Cotton mill II: link value"),
          cubes: null,
          noCanal: todo("Cotton mill II: not in canal era"),
          noRail: todo("Cotton mill II: not in rail era"),
          developable: todo("Cotton mill II: developable"),
        },
        {
          level: 3,
          locked: false,
          tiles: todo("Cotton mill III: tiles"),
          money: todo("Cotton mill III: £ cost"),
          coal: todo("Cotton mill III: coal"),
          iron: todo("Cotton mill III: iron"),
          vp: todo("Cotton mill III: VP"),
          income: todo("Cotton mill III: income"),
          link: todo("Cotton mill III: link value"),
          cubes: null,
          noCanal: todo("Cotton mill III: not in canal era"),
          noRail: todo("Cotton mill III: not in rail era"),
          developable: todo("Cotton mill III: developable"),
        },
        {
          level: 4,
          locked: false,
          tiles: todo("Cotton mill IV: tiles"),
          money: todo("Cotton mill IV: £ cost"),
          coal: todo("Cotton mill IV: coal"),
          iron: todo("Cotton mill IV: iron"),
          vp: todo("Cotton mill IV: VP"),
          income: todo("Cotton mill IV: income"),
          link: todo("Cotton mill IV: link value"),
          cubes: null,
          noCanal: todo("Cotton mill IV: not in canal era"),
          noRail: todo("Cotton mill IV: not in rail era"),
          developable: todo("Cotton mill IV: developable"),
        },
      ],
    },
    coal: {
      total: 7,
      levels: [
        {
          level: 1,
          locked: false,
          tiles: todo("Coal mine I: tiles"),
          money: todo("Coal mine I: £ cost"),
          coal: todo("Coal mine I: coal"),
          iron: todo("Coal mine I: iron"),
          vp: todo("Coal mine I: VP"),
          income: todo("Coal mine I: income"),
          link: todo("Coal mine I: link value"),
          cubes: todo("Coal mine I: cubes"),
          noCanal: todo("Coal mine I: not in canal era"),
          noRail: todo("Coal mine I: not in rail era"),
          developable: todo("Coal mine I: developable"),
        },
        {
          level: 2,
          locked: false,
          tiles: todo("Coal mine II: tiles"),
          money: todo("Coal mine II: £ cost"),
          coal: todo("Coal mine II: coal"),
          iron: todo("Coal mine II: iron"),
          vp: todo("Coal mine II: VP"),
          income: todo("Coal mine II: income"),
          link: todo("Coal mine II: link value"),
          cubes: todo("Coal mine II: cubes"),
          noCanal: todo("Coal mine II: not in canal era"),
          noRail: todo("Coal mine II: not in rail era"),
          developable: todo("Coal mine II: developable"),
        },
        {
          level: 3,
          locked: false,
          tiles: todo("Coal mine III: tiles"),
          money: todo("Coal mine III: £ cost"),
          coal: todo("Coal mine III: coal"),
          iron: todo("Coal mine III: iron"),
          vp: todo("Coal mine III: VP"),
          income: todo("Coal mine III: income"),
          link: todo("Coal mine III: link value"),
          cubes: todo("Coal mine III: cubes"),
          noCanal: todo("Coal mine III: not in canal era"),
          noRail: todo("Coal mine III: not in rail era"),
          developable: todo("Coal mine III: developable"),
        },
        {
          level: 4,
          locked: false,
          tiles: todo("Coal mine IV: tiles"),
          money: todo("Coal mine IV: £ cost"),
          coal: todo("Coal mine IV: coal"),
          iron: todo("Coal mine IV: iron"),
          vp: todo("Coal mine IV: VP"),
          income: todo("Coal mine IV: income"),
          link: todo("Coal mine IV: link value"),
          cubes: todo("Coal mine IV: cubes"),
          noCanal: todo("Coal mine IV: not in canal era"),
          noRail: todo("Coal mine IV: not in rail era"),
          developable: todo("Coal mine IV: developable"),
        },
      ],
    },
    iron: {
      total: 4,
      levels: [
        {
          level: 1,
          locked: false,
          tiles: todo("Iron works I: tiles"),
          money: todo("Iron works I: £ cost"),
          coal: todo("Iron works I: coal"),
          iron: todo("Iron works I: iron"),
          vp: todo("Iron works I: VP"),
          income: todo("Iron works I: income"),
          link: todo("Iron works I: link value"),
          cubes: todo("Iron works I: cubes"),
          noCanal: todo("Iron works I: not in canal era"),
          noRail: todo("Iron works I: not in rail era"),
          developable: todo("Iron works I: developable"),
        },
        {
          level: 2,
          locked: false,
          tiles: todo("Iron works II: tiles"),
          money: todo("Iron works II: £ cost"),
          coal: todo("Iron works II: coal"),
          iron: todo("Iron works II: iron"),
          vp: todo("Iron works II: VP"),
          income: todo("Iron works II: income"),
          link: todo("Iron works II: link value"),
          cubes: todo("Iron works II: cubes"),
          noCanal: todo("Iron works II: not in canal era"),
          noRail: todo("Iron works II: not in rail era"),
          developable: todo("Iron works II: developable"),
        },
        {
          level: 3,
          locked: false,
          tiles: todo("Iron works III: tiles"),
          money: todo("Iron works III: £ cost"),
          coal: todo("Iron works III: coal"),
          iron: todo("Iron works III: iron"),
          vp: todo("Iron works III: VP"),
          income: todo("Iron works III: income"),
          link: todo("Iron works III: link value"),
          cubes: todo("Iron works III: cubes"),
          noCanal: todo("Iron works III: not in canal era"),
          noRail: todo("Iron works III: not in rail era"),
          developable: todo("Iron works III: developable"),
        },
        {
          level: 4,
          locked: false,
          tiles: todo("Iron works IV: tiles"),
          money: todo("Iron works IV: £ cost"),
          coal: todo("Iron works IV: coal"),
          iron: todo("Iron works IV: iron"),
          vp: todo("Iron works IV: VP"),
          income: todo("Iron works IV: income"),
          link: todo("Iron works IV: link value"),
          cubes: todo("Iron works IV: cubes"),
          noCanal: todo("Iron works IV: not in canal era"),
          noRail: todo("Iron works IV: not in rail era"),
          developable: todo("Iron works IV: developable"),
        },
      ],
    },
    port: {
      total: 8,
      levels: [
        {
          level: 1,
          locked: false,
          tiles: todo("Port I: tiles"),
          money: todo("Port I: £ cost"),
          coal: todo("Port I: coal"),
          iron: todo("Port I: iron"),
          vp: todo("Port I: VP"),
          income: todo("Port I: income"),
          link: todo("Port I: link value"),
          cubes: null,
          noCanal: todo("Port I: not in canal era"),
          noRail: todo("Port I: not in rail era"),
          developable: todo("Port I: developable"),
        },
        {
          level: 2,
          locked: false,
          tiles: todo("Port II: tiles"),
          money: todo("Port II: £ cost"),
          coal: todo("Port II: coal"),
          iron: todo("Port II: iron"),
          vp: todo("Port II: VP"),
          income: todo("Port II: income"),
          link: todo("Port II: link value"),
          cubes: null,
          noCanal: todo("Port II: not in canal era"),
          noRail: todo("Port II: not in rail era"),
          developable: todo("Port II: developable"),
        },
        {
          level: 3,
          locked: false,
          tiles: todo("Port III: tiles"),
          money: todo("Port III: £ cost"),
          coal: todo("Port III: coal"),
          iron: todo("Port III: iron"),
          vp: todo("Port III: VP"),
          income: todo("Port III: income"),
          link: todo("Port III: link value"),
          cubes: null,
          noCanal: todo("Port III: not in canal era"),
          noRail: todo("Port III: not in rail era"),
          developable: todo("Port III: developable"),
        },
        {
          level: 4,
          locked: false,
          tiles: todo("Port IV: tiles"),
          money: todo("Port IV: £ cost"),
          coal: todo("Port IV: coal"),
          iron: todo("Port IV: iron"),
          vp: todo("Port IV: VP"),
          income: todo("Port IV: income"),
          link: todo("Port IV: link value"),
          cubes: null,
          noCanal: todo("Port IV: not in canal era"),
          noRail: todo("Port IV: not in rail era"),
          developable: todo("Port IV: developable"),
        },
      ],
    },
    shipyard: {
      total: 6,
      levels: [
        {
          level: 0,
          locked: true,
          tiles: todo("Shipyard level 0 (locked): tiles"),
          money: null,
          coal: null,
          iron: null,
          vp: null,
          income: null,
          link: null,
          cubes: null,
          noCanal: null,
          noRail: null,
          developable: true,
        },
        {
          level: 1,
          locked: false,
          tiles: todo("Shipyard I: tiles"),
          money: todo("Shipyard I: £ cost"),
          coal: todo("Shipyard I: coal"),
          iron: todo("Shipyard I: iron"),
          vp: todo("Shipyard I: VP"),
          income: todo("Shipyard I: income"),
          link: todo("Shipyard I: link value"),
          cubes: null,
          noCanal: todo("Shipyard I: not in canal era"),
          noRail: todo("Shipyard I: not in rail era"),
          developable: todo("Shipyard I: developable"),
        },
        {
          level: 2,
          locked: false,
          tiles: todo("Shipyard II: tiles"),
          money: todo("Shipyard II: £ cost"),
          coal: todo("Shipyard II: coal"),
          iron: todo("Shipyard II: iron"),
          vp: todo("Shipyard II: VP"),
          income: todo("Shipyard II: income"),
          link: todo("Shipyard II: link value"),
          cubes: null,
          noCanal: todo("Shipyard II: not in canal era", true),
          noRail: todo("Shipyard II: not in rail era"),
          developable: todo("Shipyard II: developable"),
        },
      ],
    },
  },
  markets: {
    coal: {
      spaces: [
        todo("Coal market: space 1 price"),
        todo("Coal market: space 2 price"),
        todo("Coal market: space 3 price"),
        todo("Coal market: space 4 price"),
        todo("Coal market: space 5 price"),
        todo("Coal market: space 6 price"),
        todo("Coal market: space 7 price"),
        todo("Coal market: space 8 price"),
      ],
      empty: 5,
    },
    iron: {
      spaces: [
        todo("Iron market: space 1 price"),
        todo("Iron market: space 2 price"),
        todo("Iron market: space 3 price"),
        todo("Iron market: space 4 price"),
        todo("Iron market: space 5 price"),
        todo("Iron market: space 6 price"),
        todo("Iron market: space 7 price"),
        todo("Iron market: space 8 price"),
      ],
      empty: 5,
    },
  },
  incomeTrack: [
    {
      income: -10,
      first: todo("Income track: £-10 first space"),
      last: todo("Income track: £-10 last space"),
    },
    {
      income: -9,
      first: todo("Income track: £-9 first space"),
      last: todo("Income track: £-9 last space"),
    },
    {
      income: -8,
      first: todo("Income track: £-8 first space"),
      last: todo("Income track: £-8 last space"),
    },
    {
      income: -7,
      first: todo("Income track: £-7 first space"),
      last: todo("Income track: £-7 last space"),
    },
    {
      income: -6,
      first: todo("Income track: £-6 first space"),
      last: todo("Income track: £-6 last space"),
    },
    {
      income: -5,
      first: todo("Income track: £-5 first space"),
      last: todo("Income track: £-5 last space"),
    },
    {
      income: -4,
      first: todo("Income track: £-4 first space"),
      last: todo("Income track: £-4 last space"),
    },
    {
      income: -3,
      first: todo("Income track: £-3 first space"),
      last: todo("Income track: £-3 last space"),
    },
    {
      income: -2,
      first: todo("Income track: £-2 first space"),
      last: todo("Income track: £-2 last space"),
    },
    {
      income: -1,
      first: todo("Income track: £-1 first space"),
      last: todo("Income track: £-1 last space"),
    },
    {
      income: 0,
      first: todo("Income track: £0 first space"),
      last: todo("Income track: £0 last space"),
    },
    {
      income: 1,
      first: todo("Income track: £1 first space"),
      last: todo("Income track: £1 last space"),
    },
    {
      income: 2,
      first: todo("Income track: £2 first space"),
      last: todo("Income track: £2 last space"),
    },
    {
      income: 3,
      first: todo("Income track: £3 first space"),
      last: todo("Income track: £3 last space"),
    },
    {
      income: 4,
      first: todo("Income track: £4 first space"),
      last: todo("Income track: £4 last space"),
    },
    {
      income: 5,
      first: todo("Income track: £5 first space"),
      last: todo("Income track: £5 last space"),
    },
    {
      income: 6,
      first: todo("Income track: £6 first space"),
      last: todo("Income track: £6 last space"),
    },
    {
      income: 7,
      first: todo("Income track: £7 first space"),
      last: todo("Income track: £7 last space"),
    },
    {
      income: 8,
      first: todo("Income track: £8 first space"),
      last: todo("Income track: £8 last space"),
    },
    {
      income: 9,
      first: todo("Income track: £9 first space"),
      last: todo("Income track: £9 last space"),
    },
    {
      income: 10,
      first: todo("Income track: £10 first space"),
      last: todo("Income track: £10 last space"),
    },
    {
      income: 11,
      first: todo("Income track: £11 first space"),
      last: todo("Income track: £11 last space"),
    },
    {
      income: 12,
      first: todo("Income track: £12 first space"),
      last: todo("Income track: £12 last space"),
    },
    {
      income: 13,
      first: todo("Income track: £13 first space"),
      last: todo("Income track: £13 last space"),
    },
    {
      income: 14,
      first: todo("Income track: £14 first space"),
      last: todo("Income track: £14 last space"),
    },
    {
      income: 15,
      first: todo("Income track: £15 first space"),
      last: todo("Income track: £15 last space"),
    },
    {
      income: 16,
      first: todo("Income track: £16 first space"),
      last: todo("Income track: £16 last space"),
    },
    {
      income: 17,
      first: todo("Income track: £17 first space"),
      last: todo("Income track: £17 last space"),
    },
    {
      income: 18,
      first: todo("Income track: £18 first space"),
      last: todo("Income track: £18 last space"),
    },
    {
      income: 19,
      first: todo("Income track: £19 first space"),
      last: todo("Income track: £19 last space"),
    },
    {
      income: 20,
      first: todo("Income track: £20 first space"),
      last: todo("Income track: £20 last space"),
    },
    {
      income: 21,
      first: todo("Income track: £21 first space"),
      last: todo("Income track: £21 last space"),
    },
    {
      income: 22,
      first: todo("Income track: £22 first space"),
      last: todo("Income track: £22 last space"),
    },
    {
      income: 23,
      first: todo("Income track: £23 first space"),
      last: todo("Income track: £23 last space"),
    },
    {
      income: 24,
      first: todo("Income track: £24 first space"),
      last: todo("Income track: £24 last space"),
    },
    {
      income: 25,
      first: todo("Income track: £25 first space"),
      last: todo("Income track: £25 last space"),
    },
    {
      income: 26,
      first: todo("Income track: £26 first space"),
      last: todo("Income track: £26 last space"),
    },
    {
      income: 27,
      first: todo("Income track: £27 first space"),
      last: todo("Income track: £27 last space"),
    },
    {
      income: 28,
      first: todo("Income track: £28 first space"),
      last: todo("Income track: £28 last space"),
    },
    {
      income: 29,
      first: todo("Income track: £29 first space"),
      last: todo("Income track: £29 last space"),
    },
    {
      income: 30,
      first: todo("Income track: £30 first space"),
      last: todo("Income track: £30 last space"),
    },
  ],
  distantMarket: {
    tiles: [
      {
        move: todo("Distant market tile 1: move"),
        players: todo("Distant market tile 1: players"),
        flagged: todo("Distant market tile 1: \"!\""),
      },
    ],
    track: [
      todo("Distant market track row 1: income"),
    ],
  },
  hubs: [
    {
      name: "The North",
      id: "the_north",
      linkValue: todo("The North: link value"),
      marketAccess: todo("The North: gives market access", true),
    },
    {
      name: "London",
      id: "london",
      linkValue: todo("London: link value"),
      marketAccess: todo("London: gives market access", true),
    },
    {
      name: "West Wales",
      id: "west_wales",
      linkValue: todo("West Wales: link value"),
      marketAccess: todo("West Wales: gives market access", true),
    },
  ],
  portTownsGiveMarketAccess: todo("Towns with a port slot give market access", true),
}
