// GENERATED from docs/TILES.md by `npm run tiles`. Don't edit: change docs/TILES.md and run it again.
// Every value is filled in; 274 still to check against the physical game.

import { unverified, type TileTable } from '../tileTable'

export const TILE_TABLE: TileTable = {
  industries: {
    cotton: {
      total: 12,
      levels: [
        {
          level: 1,
          locked: false,
          tiles: unverified("Cotton mill I: tiles", 3),
          money: unverified("Cotton mill I: £ cost", 12),
          coal: unverified("Cotton mill I: coal", 0),
          iron: unverified("Cotton mill I: iron", 0),
          vp: unverified("Cotton mill I: VP", 3),
          income: unverified("Cotton mill I: income", 5),
          link: unverified("Cotton mill I: link value", 1),
          cubes: null,
          noCanal: unverified("Cotton mill I: not in canal era", false),
          noRail: unverified("Cotton mill I: not in rail era", true),
          developable: unverified("Cotton mill I: developable", true),
        },
        {
          level: 2,
          locked: false,
          tiles: unverified("Cotton mill II: tiles", 3),
          money: unverified("Cotton mill II: £ cost", 14),
          coal: unverified("Cotton mill II: coal", 1),
          iron: unverified("Cotton mill II: iron", 0),
          vp: unverified("Cotton mill II: VP", 5),
          income: unverified("Cotton mill II: income", 4),
          link: unverified("Cotton mill II: link value", 1),
          cubes: null,
          noCanal: unverified("Cotton mill II: not in canal era", false),
          noRail: unverified("Cotton mill II: not in rail era", false),
          developable: unverified("Cotton mill II: developable", true),
        },
        {
          level: 3,
          locked: false,
          tiles: unverified("Cotton mill III: tiles", 3),
          money: unverified("Cotton mill III: £ cost", 16),
          coal: unverified("Cotton mill III: coal", 1),
          iron: unverified("Cotton mill III: iron", 1),
          vp: unverified("Cotton mill III: VP", 9),
          income: unverified("Cotton mill III: income", 3),
          link: unverified("Cotton mill III: link value", 1),
          cubes: null,
          noCanal: unverified("Cotton mill III: not in canal era", false),
          noRail: unverified("Cotton mill III: not in rail era", false),
          developable: unverified("Cotton mill III: developable", true),
        },
        {
          level: 4,
          locked: false,
          tiles: unverified("Cotton mill IV: tiles", 3),
          money: unverified("Cotton mill IV: £ cost", 18),
          coal: unverified("Cotton mill IV: coal", 1),
          iron: unverified("Cotton mill IV: iron", 1),
          vp: unverified("Cotton mill IV: VP", 12),
          income: unverified("Cotton mill IV: income", 2),
          link: unverified("Cotton mill IV: link value", 1),
          cubes: null,
          noCanal: unverified("Cotton mill IV: not in canal era", false),
          noRail: unverified("Cotton mill IV: not in rail era", false),
          developable: unverified("Cotton mill IV: developable", true),
        },
      ],
    },
    coal: {
      total: 7,
      levels: [
        {
          level: 1,
          locked: false,
          tiles: unverified("Coal mine I: tiles", 1),
          money: unverified("Coal mine I: £ cost", 5),
          coal: unverified("Coal mine I: coal", 0),
          iron: unverified("Coal mine I: iron", 0),
          vp: unverified("Coal mine I: VP", 1),
          income: unverified("Coal mine I: income", 4),
          link: unverified("Coal mine I: link value", 1),
          cubes: unverified("Coal mine I: cubes", 2),
          noCanal: unverified("Coal mine I: not in canal era", false),
          noRail: unverified("Coal mine I: not in rail era", true),
          developable: unverified("Coal mine I: developable", true),
        },
        {
          level: 2,
          locked: false,
          tiles: unverified("Coal mine II: tiles", 2),
          money: unverified("Coal mine II: £ cost", 7),
          coal: unverified("Coal mine II: coal", 0),
          iron: unverified("Coal mine II: iron", 0),
          vp: unverified("Coal mine II: VP", 2),
          income: unverified("Coal mine II: income", 7),
          link: unverified("Coal mine II: link value", 1),
          cubes: unverified("Coal mine II: cubes", 3),
          noCanal: unverified("Coal mine II: not in canal era", false),
          noRail: unverified("Coal mine II: not in rail era", false),
          developable: unverified("Coal mine II: developable", true),
        },
        {
          level: 3,
          locked: false,
          tiles: unverified("Coal mine III: tiles", 2),
          money: unverified("Coal mine III: £ cost", 8),
          coal: unverified("Coal mine III: coal", 0),
          iron: unverified("Coal mine III: iron", 1),
          vp: unverified("Coal mine III: VP", 3),
          income: unverified("Coal mine III: income", 6),
          link: unverified("Coal mine III: link value", 1),
          cubes: unverified("Coal mine III: cubes", 4),
          noCanal: unverified("Coal mine III: not in canal era", false),
          noRail: unverified("Coal mine III: not in rail era", false),
          developable: unverified("Coal mine III: developable", true),
        },
        {
          level: 4,
          locked: false,
          tiles: unverified("Coal mine IV: tiles", 2),
          money: unverified("Coal mine IV: £ cost", 10),
          coal: unverified("Coal mine IV: coal", 0),
          iron: unverified("Coal mine IV: iron", 1),
          vp: unverified("Coal mine IV: VP", 4),
          income: unverified("Coal mine IV: income", 5),
          link: unverified("Coal mine IV: link value", 1),
          cubes: unverified("Coal mine IV: cubes", 5),
          noCanal: unverified("Coal mine IV: not in canal era", false),
          noRail: unverified("Coal mine IV: not in rail era", false),
          developable: unverified("Coal mine IV: developable", true),
        },
      ],
    },
    iron: {
      total: 4,
      levels: [
        {
          level: 1,
          locked: false,
          tiles: unverified("Iron works I: tiles", 1),
          money: unverified("Iron works I: £ cost", 5),
          coal: unverified("Iron works I: coal", 1),
          iron: unverified("Iron works I: iron", 0),
          vp: unverified("Iron works I: VP", 3),
          income: unverified("Iron works I: income", 3),
          link: unverified("Iron works I: link value", 1),
          cubes: unverified("Iron works I: cubes", 4),
          noCanal: unverified("Iron works I: not in canal era", false),
          noRail: unverified("Iron works I: not in rail era", true),
          developable: unverified("Iron works I: developable", true),
        },
        {
          level: 2,
          locked: false,
          tiles: unverified("Iron works II: tiles", 1),
          money: unverified("Iron works II: £ cost", 7),
          coal: unverified("Iron works II: coal", 1),
          iron: unverified("Iron works II: iron", 0),
          vp: unverified("Iron works II: VP", 5),
          income: unverified("Iron works II: income", 3),
          link: unverified("Iron works II: link value", 1),
          cubes: unverified("Iron works II: cubes", 4),
          noCanal: unverified("Iron works II: not in canal era", false),
          noRail: unverified("Iron works II: not in rail era", false),
          developable: unverified("Iron works II: developable", true),
        },
        {
          level: 3,
          locked: false,
          tiles: unverified("Iron works III: tiles", 1),
          money: unverified("Iron works III: £ cost", 9),
          coal: unverified("Iron works III: coal", 1),
          iron: unverified("Iron works III: iron", 0),
          vp: unverified("Iron works III: VP", 7),
          income: unverified("Iron works III: income", 2),
          link: unverified("Iron works III: link value", 1),
          cubes: unverified("Iron works III: cubes", 5),
          noCanal: unverified("Iron works III: not in canal era", false),
          noRail: unverified("Iron works III: not in rail era", false),
          developable: unverified("Iron works III: developable", true),
        },
        {
          level: 4,
          locked: false,
          tiles: unverified("Iron works IV: tiles", 1),
          money: unverified("Iron works IV: £ cost", 12),
          coal: unverified("Iron works IV: coal", 1),
          iron: unverified("Iron works IV: iron", 0),
          vp: unverified("Iron works IV: VP", 9),
          income: unverified("Iron works IV: income", 1),
          link: unverified("Iron works IV: link value", 1),
          cubes: unverified("Iron works IV: cubes", 6),
          noCanal: unverified("Iron works IV: not in canal era", false),
          noRail: unverified("Iron works IV: not in rail era", false),
          developable: unverified("Iron works IV: developable", true),
        },
      ],
    },
    port: {
      total: 8,
      levels: [
        {
          level: 1,
          locked: false,
          tiles: unverified("Port I: tiles", 2),
          money: unverified("Port I: £ cost", 6),
          coal: unverified("Port I: coal", 0),
          iron: unverified("Port I: iron", 0),
          vp: unverified("Port I: VP", 2),
          income: unverified("Port I: income", 3),
          link: unverified("Port I: link value", 1),
          cubes: null,
          noCanal: unverified("Port I: not in canal era", false),
          noRail: unverified("Port I: not in rail era", true),
          developable: unverified("Port I: developable", true),
        },
        {
          level: 2,
          locked: false,
          tiles: unverified("Port II: tiles", 2),
          money: unverified("Port II: £ cost", 7),
          coal: unverified("Port II: coal", 0),
          iron: unverified("Port II: iron", 0),
          vp: unverified("Port II: VP", 4),
          income: unverified("Port II: income", 3),
          link: unverified("Port II: link value", 1),
          cubes: null,
          noCanal: unverified("Port II: not in canal era", false),
          noRail: unverified("Port II: not in rail era", false),
          developable: unverified("Port II: developable", true),
        },
        {
          level: 3,
          locked: false,
          tiles: unverified("Port III: tiles", 2),
          money: unverified("Port III: £ cost", 8),
          coal: unverified("Port III: coal", 0),
          iron: unverified("Port III: iron", 0),
          vp: unverified("Port III: VP", 6),
          income: unverified("Port III: income", 4),
          link: unverified("Port III: link value", 1),
          cubes: null,
          noCanal: unverified("Port III: not in canal era", false),
          noRail: unverified("Port III: not in rail era", false),
          developable: unverified("Port III: developable", true),
        },
        {
          level: 4,
          locked: false,
          tiles: unverified("Port IV: tiles", 2),
          money: unverified("Port IV: £ cost", 9),
          coal: unverified("Port IV: coal", 0),
          iron: unverified("Port IV: iron", 0),
          vp: unverified("Port IV: VP", 9),
          income: unverified("Port IV: income", 4),
          link: unverified("Port IV: link value", 1),
          cubes: null,
          noCanal: unverified("Port IV: not in canal era", false),
          noRail: unverified("Port IV: not in rail era", false),
          developable: unverified("Port IV: developable", true),
        },
      ],
    },
    shipyard: {
      total: 6,
      levels: [
        {
          level: 0,
          locked: true,
          tiles: unverified("Shipyard level 0 (locked): tiles", 2),
          money: null,
          coal: null,
          iron: null,
          vp: null,
          income: null,
          link: null,
          cubes: null,
          noCanal: null,
          noRail: null,
          developable: true,
        },
        {
          level: 1,
          locked: false,
          tiles: unverified("Shipyard I: tiles", 2),
          money: unverified("Shipyard I: £ cost", 16),
          coal: unverified("Shipyard I: coal", 1),
          iron: unverified("Shipyard I: iron", 1),
          vp: unverified("Shipyard I: VP", 10),
          income: unverified("Shipyard I: income", 2),
          link: unverified("Shipyard I: link value", 1),
          cubes: null,
          noCanal: unverified("Shipyard I: not in canal era", false),
          noRail: unverified("Shipyard I: not in rail era", false),
          developable: unverified("Shipyard I: developable", true),
        },
        {
          level: 2,
          locked: false,
          tiles: unverified("Shipyard II: tiles", 2),
          money: unverified("Shipyard II: £ cost", 25),
          coal: unverified("Shipyard II: coal", 1),
          iron: unverified("Shipyard II: iron", 1),
          vp: unverified("Shipyard II: VP", 18),
          income: unverified("Shipyard II: income", 1),
          link: unverified("Shipyard II: link value", 1),
          cubes: null,
          noCanal: unverified("Shipyard II: not in canal era", true),
          noRail: unverified("Shipyard II: not in rail era", false),
          developable: unverified("Shipyard II: developable", true),
        },
      ],
    },
  },
  incomeTrack: [
    {
      income: -10,
      first: unverified("Income track: £-10 first space", 0),
      last: unverified("Income track: £-10 last space", 0),
    },
    {
      income: -9,
      first: unverified("Income track: £-9 first space", 1),
      last: unverified("Income track: £-9 last space", 1),
    },
    {
      income: -8,
      first: unverified("Income track: £-8 first space", 2),
      last: unverified("Income track: £-8 last space", 2),
    },
    {
      income: -7,
      first: unverified("Income track: £-7 first space", 3),
      last: unverified("Income track: £-7 last space", 3),
    },
    {
      income: -6,
      first: unverified("Income track: £-6 first space", 4),
      last: unverified("Income track: £-6 last space", 4),
    },
    {
      income: -5,
      first: unverified("Income track: £-5 first space", 5),
      last: unverified("Income track: £-5 last space", 5),
    },
    {
      income: -4,
      first: unverified("Income track: £-4 first space", 6),
      last: unverified("Income track: £-4 last space", 6),
    },
    {
      income: -3,
      first: unverified("Income track: £-3 first space", 7),
      last: unverified("Income track: £-3 last space", 7),
    },
    {
      income: -2,
      first: unverified("Income track: £-2 first space", 8),
      last: unverified("Income track: £-2 last space", 8),
    },
    {
      income: -1,
      first: unverified("Income track: £-1 first space", 9),
      last: unverified("Income track: £-1 last space", 9),
    },
    {
      income: 0,
      first: unverified("Income track: £0 first space", 10),
      last: unverified("Income track: £0 last space", 10),
    },
    {
      income: 1,
      first: unverified("Income track: £1 first space", 11),
      last: unverified("Income track: £1 last space", 12),
    },
    {
      income: 2,
      first: unverified("Income track: £2 first space", 13),
      last: unverified("Income track: £2 last space", 14),
    },
    {
      income: 3,
      first: unverified("Income track: £3 first space", 15),
      last: unverified("Income track: £3 last space", 16),
    },
    {
      income: 4,
      first: unverified("Income track: £4 first space", 17),
      last: unverified("Income track: £4 last space", 18),
    },
    {
      income: 5,
      first: unverified("Income track: £5 first space", 19),
      last: unverified("Income track: £5 last space", 20),
    },
    {
      income: 6,
      first: unverified("Income track: £6 first space", 21),
      last: unverified("Income track: £6 last space", 22),
    },
    {
      income: 7,
      first: unverified("Income track: £7 first space", 23),
      last: unverified("Income track: £7 last space", 24),
    },
    {
      income: 8,
      first: unverified("Income track: £8 first space", 25),
      last: unverified("Income track: £8 last space", 26),
    },
    {
      income: 9,
      first: unverified("Income track: £9 first space", 27),
      last: unverified("Income track: £9 last space", 28),
    },
    {
      income: 10,
      first: unverified("Income track: £10 first space", 29),
      last: unverified("Income track: £10 last space", 30),
    },
    {
      income: 11,
      first: unverified("Income track: £11 first space", 31),
      last: unverified("Income track: £11 last space", 33),
    },
    {
      income: 12,
      first: unverified("Income track: £12 first space", 34),
      last: unverified("Income track: £12 last space", 36),
    },
    {
      income: 13,
      first: unverified("Income track: £13 first space", 37),
      last: unverified("Income track: £13 last space", 39),
    },
    {
      income: 14,
      first: unverified("Income track: £14 first space", 40),
      last: unverified("Income track: £14 last space", 42),
    },
    {
      income: 15,
      first: unverified("Income track: £15 first space", 43),
      last: unverified("Income track: £15 last space", 45),
    },
    {
      income: 16,
      first: unverified("Income track: £16 first space", 46),
      last: unverified("Income track: £16 last space", 48),
    },
    {
      income: 17,
      first: unverified("Income track: £17 first space", 49),
      last: unverified("Income track: £17 last space", 51),
    },
    {
      income: 18,
      first: unverified("Income track: £18 first space", 52),
      last: unverified("Income track: £18 last space", 54),
    },
    {
      income: 19,
      first: unverified("Income track: £19 first space", 55),
      last: unverified("Income track: £19 last space", 57),
    },
    {
      income: 20,
      first: unverified("Income track: £20 first space", 58),
      last: unverified("Income track: £20 last space", 60),
    },
    {
      income: 21,
      first: unverified("Income track: £21 first space", 61),
      last: unverified("Income track: £21 last space", 64),
    },
    {
      income: 22,
      first: unverified("Income track: £22 first space", 65),
      last: unverified("Income track: £22 last space", 68),
    },
    {
      income: 23,
      first: unverified("Income track: £23 first space", 69),
      last: unverified("Income track: £23 last space", 72),
    },
    {
      income: 24,
      first: unverified("Income track: £24 first space", 73),
      last: unverified("Income track: £24 last space", 76),
    },
    {
      income: 25,
      first: unverified("Income track: £25 first space", 77),
      last: unverified("Income track: £25 last space", 80),
    },
    {
      income: 26,
      first: unverified("Income track: £26 first space", 81),
      last: unverified("Income track: £26 last space", 84),
    },
    {
      income: 27,
      first: unverified("Income track: £27 first space", 85),
      last: unverified("Income track: £27 last space", 88),
    },
    {
      income: 28,
      first: unverified("Income track: £28 first space", 89),
      last: unverified("Income track: £28 last space", 92),
    },
    {
      income: 29,
      first: unverified("Income track: £29 first space", 93),
      last: unverified("Income track: £29 last space", 96),
    },
    {
      income: 30,
      first: unverified("Income track: £30 first space", 97),
      last: unverified("Income track: £30 last space", 100),
    },
  ],
  hubs: [
    {
      name: "The North",
      id: "the_north",
      linkValue: unverified("The North: link value", 2),
      marketAccess: true,
    },
    {
      name: "London",
      id: "london",
      linkValue: unverified("London: link value", 2),
      marketAccess: true,
    },
    {
      name: "West Wales",
      id: "west_wales",
      linkValue: unverified("West Wales: link value", 2),
      marketAccess: true,
    },
  ],
  portTownsGiveMarketAccess: true,
}
