// Bundles the game server (src/server/edge.ts: the rules engine, the game server, the ratings) into one
// dependency-free ES module for the Supabase Edge Function: supabase/functions/_shared/game-server.js.
//   npm run build:server           write it
//   node scripts/build-server.mjs --check   fail if it's out of date (the tests run this too)
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { rolldown } from 'rolldown'

const root = new URL('..', import.meta.url)
const entry = fileURLToPath(new URL('src/server/edge.ts', root))
export const TARGET = fileURLToPath(new URL('supabase/functions/_shared/game-server.js', root))
const BANNER = `// GENERATED by \`npm run build:server\` from src/server/edge.ts (the rules engine and game server the browser uses).
// Don't edit: change the source and run it again. Deno runs this in supabase/functions/game.
`

export async function buildServer() {
  // Vite-only flags the shared code reads: the server is never a development build.
  const bundle = await rolldown({ input: entry, logLevel: 'silent', platform: 'neutral', transform: { define: { 'import.meta.env.DEV': 'false', 'import.meta.env.PROD': 'true' } } })
  const { output } = await bundle.generate({ format: 'esm' })
  await bundle.close()
  return BANNER + output[0].code
}

/** True when the committed bundle matches the current source. */
export async function serverBundleIsFresh() {
  try {
    return readFileSync(TARGET, 'utf8') === (await buildServer())
  } catch {
    return false
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  if (process.argv.includes('--check')) {
    if (!(await serverBundleIsFresh())) {
      console.error('supabase/functions/_shared/game-server.js is out of date: run `npm run build:server`.')
      process.exit(1)
    }
    console.log('supabase/functions/_shared/game-server.js is up to date.')
  } else {
    const code = await buildServer()
    writeFileSync(TARGET, code)
    console.log(`Wrote supabase/functions/_shared/game-server.js (${Math.round(code.length / 1024)} kB).`)
  }
}
